boards/api/urls.py
from django.urls import path
from .views import (
    BoardList,
    BoardDetail,
    BoardTopicList,
    TopicPostList,
    ProfileView,
)

urlpatterns = [
    path('', BoardList.as_view(), name='board-list'),
    path('board/<slug:slug>/', BoardDetail.as_view(), name='board-detail'),
    path('board/<slug:slug>/topics/', BoardTopicList.as_view(), name='board-topic-list'),
    path('board/<slug:slug>/topics/<slug:topic_slug>/', TopicPostList.as_view(), name='topic-post-list'),
    path('profile/', ProfileView.as_view(), name='user-profile'),
]

boards/urls.py
from django.urls import path
from .views import BoardTopicsView, TopicPostsView,  NewBoardTopicView, NewTopicPostView, PostUpdateView, SearchView, markdown_uploader
from pages.views import HomeView
app_name = 'boards'

urlpatterns = [
    path('boards/<slug:board_slug>/', BoardTopicsView.as_view(), name='board_topics' ),
    path('boards/<slug:board_slug>/topics/<slug:topic_slug>-<int:topic_pk>/', TopicPostsView.as_view(), name='topic_posts' ),
    path('boards/<slug:board_slug>/create-new/', NewBoardTopicView.as_view(), name='new_board_topic' ),
    path('boards/<slug:board_slug>/topics/<slug:topic_slug>-<int:topic_pk>/reply/', NewTopicPostView.as_view(), name='new_topic_post' ),
    path('boards/<slug:board_slug>/topics/<slug:topic_slug>-<int:topic_pk>/posts/<int:pk>/edit/', PostUpdateView.as_view(), name='post_update' ),
    path('search/', SearchView.as_view(), name='search'),
    path('api/uploader/', markdown_uploader, name='markdown_uploader_page'),
]

forum/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('admin@jokotoye18/', admin.site.urls),
    # path('rest-auth/', include('rest_auth.urls')),
    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('martor/', include('martor.urls')),
    path('', include('pages.urls')),
    path('account/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('boards.urls')),
    # path('api/', include('boards.api.urls')),
]

# urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

admin.site.site_header = "Forum Admin"
admin.site.site_title = "Forum Admin Portal"
admin.site.index_title = "Welcome to Forum Portal"

boards/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.html import mark_safe
from markdown import markdown
from django.template.defaultfilters import slugify
from martor.models import MartorField


BADGES_CATEGORY = (
    ('P', 'primary'),
    ('S', 'success'),
    ('D', 'dark'),
    ('W', 'warning'),
)

class Board(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=200)
    badge = models.CharField(max_length=1, choices=BADGES_CATEGORY)
    slug = models.SlugField(blank=True, max_length=100)

    objects = models.Manager()


    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_post_count(self):
        post_count = Post.objects.filter(topic__board=self).count()
        return post_count

    def get_last_post(self):
        last_post = Post.objects.filter(topic__board=self).order_by("-created_on").first()
        return last_post
        
    def get_last_post_API(self):
        last_post = Post.objects.filter(topic__board=self).order_by("-created_on").first()
        if last_post:
            return last_post.created_by
        return 'No post yet'

class Topic(models.Model):
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    topic = models.CharField(max_length=200, unique=True) 
    slug = models.SlugField(blank=True, max_length=200)
    views = models.PositiveIntegerField(default=0)
    starter = models.ForeignKey(get_user_model(), related_name="topics", on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    def __str__(self):
        return self.topic


    def save(self, *args, **kwargs):
        self.slug = slugify(self.topic)
        return super().save(*args, **kwargs)
    

class Post(models.Model):
    topic = models.ForeignKey(Topic, related_name='posts',on_delete=models.CASCADE)
    post = MartorField()
    slug = models.SlugField(blank=True, max_length=200)
    created_by = models.ForeignKey(get_user_model(), related_name='posts', on_delete=models.CASCADE)
    updated_by = models.ForeignKey(get_user_model(), related_name="+", on_delete=models.CASCADE, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()


    def __str__(self):
        return self.post

    def save(self, *args, **kwargs):
        self.slug = slugify(self.topic)
        return super().save(*args, **kwargs)

    def get_post_as_markdown(self):
        return mark_safe(markdown(self.post, safe_mode='escape'))
    

boards/api/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from accounts.models import Profile
from boards.models import Board, Topic, Post
from rest_framework.response import Response
from rest_framework.parsers import FormParser
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework import status
from rest_framework.reverse import reverse
from rest_framework.views import APIView
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView, ListAPIView, RetrieveUpdateAPIView
from .serializers import BoardSerializer, TopicSerializer, PostSerializer, UserProfileSerializer

class BoardList(ListAPIView):
    queryset = Board.objects.all()
    serializer_class = BoardSerializer
    filter_fields = [
        'name',
    ]
    search_fields = [
        'name',
    ]
    ordering_fields = [
        'name',
    ]

class BoardDetail(RetrieveUpdateDestroyAPIView):
    queryset = Board.objects.all()
    serializer_class = BoardSerializer
    lookup_field = 'slug'

class BoardTopicList(ListCreateAPIView):
    serializer_class = TopicSerializer
    lookup_field = 'board__slug'
    def get_queryset(self):
        queryset = Topic.objects.filter(board__slug=self.kwargs.get('slug'))
        return queryset

    def post(self, request, *args, **kwargs):
        board = get_object_or_404(Board, slug=self.kwargs.get('slug'))
        serializer = TopicSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(board=board, starter=request.user)
            # Post.objects.create(
            #     topic=request.data.get('topic'),
            #     subject = request.data.get('subject'),
            #     created_by = request.user
            # )
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



class TopicPostList(APIView):
    def get(self, request, *args, **kwargs):
        subject = Post.objects.filter(topic__slug=self.kwargs.get('topic_slug')).first()
        replies = Post.objects.filter(topic__slug=self.kwargs.get('topic_slug'))[1:]
        if replies:
            subject_serializer = PostSerializer(subject)
            replies_serializer = PostSerializer(replies, many=True)
            return Response({
                'subject': subject_serializer.data,
                'replies': replies_serializer.data
            })
        else:
            subject_serializer = PostSerializer(subject)
            return Response({
                'subject': subject_serializer.data,
                'replies': 'No reply yet!'
            })

    def post(self, request, *args, **kwargs):
        topic = get_object_or_404(Topic, slug=self.kwargs.get('topic_slug'))
        serializer = PostSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(topic=topic, created_by=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class ProfileView(RetrieveUpdateAPIView):
    serializer_class = UserProfileSerializer
    queryset = Profile.objects.all()
    lookup_field = 'user__username'
    lookup_url_kwarg = 'username'

    # def get(self, request, *args, **kwargs):
    #     profile = get_object_or_404(Profile, user__username=self.kwargs.get('username'))
    #     serializer = UserProfileSerializer(profile)
    #     return Response(serializer.data)

    # def patch(self, request, *args, **kwargs):
    #     profile = get_object_or_404(Profile, user__username=self.kwargs.get('username'))
    #     serializer = UserProfileSerializer(profile, data=request.data)
    #     if serializer.is_valid():
    #         serializer.save()
    #         return Response(serializer.data, status=status.HTTP_201_CREATED)
    #     return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

boards/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib import messages
from django.http import Http404, HttpResponse
from django.db.models import Q
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Board, Topic, Post
from .forms import  NewTopicForm, NewTopicPostForm
from django.contrib.auth.models import User
from django.views.generic import ListView, CreateView,DetailView, View
from django.views.generic.edit import UpdateView, DeleteView
from django.utils import timezone
from django.contrib.admin.views.decorators import staff_member_required
from allauth.account.views import PasswordChangeView

#martor image uploader
import os
import json
import uuid

from django.conf import settings
from django.http import HttpResponse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile

from martor.utils import LazyEncoder


class BoardTopicsView(View):
    def get(self, request, *args, **kwargs):
        board = get_object_or_404(Board, slug=self.kwargs['board_slug'])
        board_topics = board.topics.order_by('-created_on')
        context = {'board':board, 'board_topics': board_topics}
        return render(request, 'boards/board_topics.html', context)



class NewBoardTopicView(LoginRequiredMixin, View):
    login_url = 'account_login'
    redirect_field_name = 'next'
    def get(self, request, *args, **kwargs):
        form = NewTopicForm()
        context = {'form': form}
        return render(request, 'boards/new_board_topic.html', context)


    def post(self, request, *args, **kwargs):
        board = get_object_or_404(Board, slug=self.kwargs['board_slug'])
        form = NewTopicForm(request.POST)
        if form.is_valid() and form is not None:
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = request.user
            topic.save()
            post = request.POST.get('subject')
            post = Post.objects.create(
                topic = topic,
                post = post,
                created_by = request.user
            )
            messages.success(request, 'Topic created successfully')
            # Todo : change the redirect url
            return redirect(reverse("boards:board_topics", kwargs={"board_slug":board.slug}))
        messages.warning(request, 'ValueError! Invalid input')
        return redirect(reverse("boards:new_board_topic", kwargs={"board_slug":board.slug}))



class TopicPostsView(View):
    def get(self, request, *args, **kwargs):
        topic = get_object_or_404(Topic, slug=self.kwargs.get('topic_slug'), pk=self.kwargs.get('topic_pk'))
        session_key = 'viewed_topic_{}'.format(topic.pk)
        print(session_key)
        if not request.session.get(session_key, False):
            topic.views += 1
            topic.save()
            request.session[session_key] = True
        subject = topic.posts.first()
        replies = topic.posts.all()[1:]
        print(request.session[session_key])
        context = {'topic':topic, 'subject': subject, 'replies': replies}
        return render(request, 'boards/topic_posts.html', context)

class NewTopicPostView(LoginRequiredMixin, View):
    login_url = 'account_login'
    redirect_field_name = 'next'
    def get(self, request, *args, **kwargs):
        form = NewTopicPostForm()
        topic = get_object_or_404(Topic, slug=self.kwargs["topic_slug"], pk=self.kwargs["topic_pk"])
        subject = topic.posts.first()
        replies = topic.posts.all()[1:]
        context = {"form":form, "topic": topic, "subject":subject, "replies": replies}
        return render(request, "boards/new_topic_post.html", context)


    def post(self, request, *args, **kwargs):
        form = NewTopicPostForm(data=request.POST)
        topic = get_object_or_404(Topic, slug=self.kwargs["topic_slug"], pk=self.kwargs["topic_pk"])
        if form.is_valid() and form is not None:
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()
            topic.updated_on = timezone.now()
            topic.save()
            messages.info(request, 'Reply successfully added')
            return redirect(reverse("boards:topic_posts", kwargs={"board_slug":topic.board.slug, "topic_slug":topic.slug, "topic_pk":topic.pk}))
        messages.warning(request, 'ValueError! Invalid input')
        return redirect(reverse("boards:new_topic_post", kwargs={"board_slug":topic.board.slug, 'topic_slug':topic.slug, 'topic_pk': topic.pk}))


class PostUpdateView(LoginRequiredMixin, View):
    login_url = 'account_login'
    redirect_field_name = 'next'
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        form = NewTopicPostForm(instance=post)
        context = {'form': form, 'post':post}
        return render(request, 'boards/post_update.html', context)

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        topic = post.topic
        form = NewTopicPostForm(instance=post, data=request.POST)
        if form.is_valid() and form is not None:
            post = form.save()
            post.updated_on = timezone.now()
            messages.info(request, 'post updated successfully')
            return redirect(reverse("boards:topic_posts", kwargs={"board_slug":topic.board.slug, "topic_slug":topic.slug, "topic_pk":topic.pk}))
        messages.warning(request, 'ValueError! Invalid input')
        return redirect(reverse("boards:topic_posts", kwargs={"board_slug":topic.board.slug, "topic_slug":topic.slug, "topic_pk":topic.pk}))

class SearchView(View):
    def get(self, request, *args, **kwargs):
        q = request.GET.get('q', None)
        if q is None:
            search_list = []
        elif str(q).strip() ==  '':
            search_list = []
        else:
            search_list = Topic.objects.filter(topic__icontains=q)
            search_list = search_list.order_by('topic')       
        context = {'search_list': search_list, 'q':q}
        return render(request, 'search.html', context)






@login_required
def markdown_uploader(request):
    """
    Makdown image upload for locale storage
    and represent as json to markdown editor.
    """
    if request.method == 'POST' and request.is_ajax():
        if 'markdown-image-upload' in request.FILES:
            image = request.FILES['markdown-image-upload']
            image_types = [
                'image/png', 'image/jpg',
                'image/jpeg', 'image/pjpeg', 'image/gif'
            ]
            if image.content_type not in image_types:
                data = json.dumps({
                    'status': 405,
                    'error': _('Bad image format.')
                }, cls=LazyEncoder)
                return HttpResponse(
                    data, content_type='application/json', status=405)

            if image._size > settings.MAX_IMAGE_UPLOAD_SIZE:
                to_MB = settings.MAX_IMAGE_UPLOAD_SIZE / (1024 * 1024)
                data = json.dumps({
                    'status': 405,
                    'error': _('Maximum image file is %(size) MB.') % {'size': to_MB}
                }, cls=LazyEncoder)
                return HttpResponse(
                    data, content_type='application/json', status=405)

            img_uuid = "{0}-{1}".format(uuid.uuid4().hex[:10], image.name.replace(' ', '-'))
            tmp_file = os.path.join(settings.MARTOR_UPLOAD_PATH, img_uuid)
            def_path = default_storage.save(tmp_file, ContentFile(image.read()))
            img_url = os.path.join(settings.MEDIA_URL, def_path)

            data = json.dumps({
                'status': 200,
                'link': img_url,
                'name': image.name
            })
            return HttpResponse(data, content_type='application/json')
        return HttpResponse(_('Invalid request!'))
    return HttpResponse(_('Invalid request!'))

templates/boards/board_topics.html
{% extends 'base.html' %}
{% load static %}
{%  load substract %}
{% load humanize %} 
{% block title %}Forum-{{ board.name }}{% endblock %}


{% block content %}
<div class="container my-5">
    <main role="main">
        <div class="row justify-content-center">
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        <h2 class="text-center ">Welcome to {{ board }} board!</h2>
                        <p>{{ board.description }}</p>
                    </div>
                    <div class="card-body">
                        <div class="text-center my-2">
                            <a class="btn btn-info btn-block" href="{% url 'boards:new_board_topic' board.slug %}">Add New Topic</a>
                        </div>
                        <div class="table-responsive-md">
                            {% if board_topics %}
                            <table class="table table-hover table-bordered ">
                                <thead class="thead-dark">
                                    <tr>
                                        <th scope="col">#</td>
                                        <th scope="col">Topic</th>
                                        <th scope="col">Starter</th>
                                        <th scope="col">Replies</th>
                                        <th scope="col">Views</th>
                                        <th scope="col">Last Updated</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for topic in board_topics %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>
                                            <a href="{% url 'boards:topic_posts' board.slug topic.slug topic.pk %}">{{ topic }}</a>
                                        </td>
                                        <td class="align-middle">{{ topic.starter }}</td>
                                        <td class="align-middle">{{ topic.posts.count|substract_by:1 }}</td>
                                        <td class="align-middle">{{ topic.views }}</td>
                                        <td class="">{{ topic.posts.last.created_on|naturaltime }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </main>
</div>
{% endblock content %}

templates/boards/new_board_topic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Forum-create-new-topic{% endblock %}
{% block javascript %}
{% endblock %}




{% block content %}
<main class="container my-5" role="main">
    <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card">
                <div class="card-header text-center">
                    <h3>Add new topic here!</h3>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{form.media }}
                        {{form|crispy }}
                        <button class="btn btn-dark">Add Topic</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/boards/new_topic_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %} 
{% load bleach %}
{% load gravatar %}
{% load martortags %}
{% block title %}Forum-{{ topic }} reply{% endblock %}







{% block content %}
<main class="container my-5" role="main">
    <div class="row justify-content-center">
        <div class="col-md-9">
            <section style="margin-bottom: 8rem;" class="card">
                <div class="text-center card-header">
                    <h3>Reply</h3>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{form.media }}
                        {{form|crispy }}
                        <button class="btn btn-dark">reply</button>
                        <!-- <input type="button" role="button" value="reply" class="btn btn-dark"> -->
                    </form>
                </div>
            </section>
            <button  class="btn btn-info">Subject</button>
            <section style="margin-bottom: 2rem;" class="card mt-3">
                <div class="card-body">
                    <div class=" p-4 border border-dark mb-4">
                        <div class="mb-2">
                            <small class="badge badge-pill badge-primary">Created by {{ subject.created_by.username }} | {{ subject.created_on|naturaltime }}</small>
                        </div>
                        <div class="row">
                            <div class="col-2">
                                <img src="{{ subject.created_by|gravatar_img }}" alt="{{ subject.created_by.username }}" class="w-100 rounded">
                            </div>
                            <div class="col-10">
                                <p class="p-0 m-0">{{ subject.post|safe_markdown|rich_text }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {% if replies %}
            <button  class="btn btn-info">Reply</button>
            <div class="card mt-3">
                <section class="card-body ">
                    {% for reply in replies %}
                        <div class="p-4 border border-dark mb-4">
                            <div class="mb-2">
                                <small class="badge badge-pill badge-{{ reply.topic.board.get_badge_display }}">Created by {{ reply.created_by.username }} | {{ reply.created_on|naturaltime }}</small>
                            </div>
                            <div class="row">
                                <div class="col-2">
                                    <img src="{{ reply.created_by|gravatar_img }}" alt="{{ reply.created_by.username }}" class="w-100 rounded">
                                </div>
                                <div class="col-10">
                                    <p class="p-0 m-0">{{ reply.post|safe_markdown|rich_text  }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </section>
            </div>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}

templates/boards/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Forum-Edit{% endblock %}

{% block content %}
<main class="container my-5" role="main">
    <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card">
                <div class="text-center card-header">
                    <h3>Edit your post here!</h3>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{form.media }}
                        {{form|crispy }}
                        <button class="btn btn-dark">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/boards/topic_posts.html
{% extends 'base.html' %}
{% load humanize %} 
{% load gravatar %}
{% load bleach %}
{% load static %}
{% load martortags %}

{% block title %}Forum-{{ topic }}{% endblock %}



{% block content %}
    <div class="container my-5">
        <main role="main">
            <div class="row justify-content-center">
                <div class="col-md-9">
                    <section class="card">
                        <div class="card-header">
                            <h4>{{ topic }}</h4>
                            <small class="badge badge-pill badge-{{ topic.board.get_badge_display }}">{{ topic.board }}</small>
                        </div>
                    </section>
                    <section style="margin-bottom: 8rem;" class="card">
                        <div class="card-body">
                            <div class=" p-4 border border-dark mb-4">
                                <div class="mb-2">
                                    <small class="badge badge-pill badge-primary">Created by {{ subject.created_by }} | {{ subject.created_on|naturaltime }}</small>
                                </div>
                                <div class="row">
                                    <div class="col-2">
                                        <img src="{{ subject.created_by|gravatar_img }}" alt="{{ subject.created_by.username }}" class="w-100 rounded">
                                    </div>
                                    <div class="col-10">
                                        <p class="p-0 m-0">{{ subject.post|safe_markdown|rich_text  }}</p>
                                    </div>
                                </div>                                
                                {% if subject.created_by == request.user %}
                                    <a class="btn btn-info" href="{% url 'boards:post_update' topic.board.slug topic.slug topic.pk subject.pk %}">Edit</a>
                                {% endif %}
                            </div>
                            <div class="">
                                <a class="btn btn-dark" href="{% url 'boards:new_topic_post' topic.board.slug topic.slug topic.pk %}">Reply</a>
                            </div>
                        </div>
                    </section>
                    {% if replies %}
                    <div class="card">
                        <section class="card-body ">
                            {% for reply in replies %}
                                <div class="p-4 border border-dark mb-4">
                                    <div class="mb-2">
                                        <small class="badge badge-pill badge-dark">Created by {{ reply.created_by }} | {{ reply.created_on|naturaltime }}</small>
                                    </div>
                                    <div class="row">
                                        <div class="col-2">
                                            <img src="{{ reply.created_by|gravatar_img }}" alt="{{ reply.created_by.username }}" class="w-100 rounded">
                                        </div>
                                        <div class="col-10">
                                            <p class="p-0 m-0">{{ reply.post|safe_markdown|rich_text  }}</p>
                                        </div>
                                    </div>
                                    {% if reply.created_by == request.user %}
                                        <a class="btn btn-info" href="{% url 'boards:post_update' topic.board.slug topic.slug topic.pk reply.pk %}">Edit</a>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </section>
                    </div>
                    {% endif %}
                </div>
            </div>
        </main>
    </div>
{% endblock %}