accounts/urls.py
from django.urls import path
from .views import UserProfileView

app_name = 'profiles'

urlpatterns = [
    path('profile/', UserProfileView.as_view(), name='profile'),
]

boards/urls.py
from django.urls import path
from .views import BoardTopicsView, TopicPostsView,  NewBoardTopicView, NewTopicPostView, PostUpdateView, SearchView, markdown_uploader
from pages.views import HomeView
app_name = 'boards'

urlpatterns = [
    path('boards/<slug:board_slug>/', BoardTopicsView.as_view(), name='board_topics' ),
    path('boards/<slug:board_slug>/topics/<slug:topic_slug>-<int:topic_pk>/', TopicPostsView.as_view(), name='topic_posts' ),
    path('boards/<slug:board_slug>/create-new/', NewBoardTopicView.as_view(), name='new_board_topic' ),
    path('boards/<slug:board_slug>/topics/<slug:topic_slug>-<int:topic_pk>/reply/', NewTopicPostView.as_view(), name='new_topic_post' ),
    path('boards/<slug:board_slug>/topics/<slug:topic_slug>-<int:topic_pk>/posts/<int:pk>/edit/', PostUpdateView.as_view(), name='post_update' ),
    path('search/', SearchView.as_view(), name='search'),
    path('api/uploader/', markdown_uploader, name='markdown_uploader_page'),
]

forum/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('admin@jokotoye18/', admin.site.urls),
    # path('rest-auth/', include('rest_auth.urls')),
    # path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('martor/', include('martor.urls')),
    path('', include('pages.urls')),
    path('account/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('boards.urls')),
    # path('api/', include('boards.api.urls')),
]

# urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

admin.site.site_header = "Forum Admin"
admin.site.site_title = "Forum Admin Portal"
admin.site.index_title = "Welcome to Forum Portal"

pages/urls.py
from django.urls import path
from .views import HomeView
app_name = 'pages'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

boards/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.html import mark_safe
from markdown import markdown
from django.template.defaultfilters import slugify
from martor.models import MartorField


BADGES_CATEGORY = (
    ('P', 'primary'),
    ('S', 'success'),
    ('D', 'dark'),
    ('W', 'warning'),
)

class Board(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=200)
    badge = models.CharField(max_length=1, choices=BADGES_CATEGORY)
    slug = models.SlugField(blank=True, max_length=100)

    objects = models.Manager()


    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_post_count(self):
        post_count = Post.objects.filter(topic__board=self).count()
        return post_count

    def get_last_post(self):
        last_post = Post.objects.filter(topic__board=self).order_by("-created_on").first()
        return last_post
        
    def get_last_post_API(self):
        last_post = Post.objects.filter(topic__board=self).order_by("-created_on").first()
        if last_post:
            return last_post.created_by
        return 'No post yet'

class Topic(models.Model):
    board = models.ForeignKey(Board, related_name='topics', on_delete=models.CASCADE)
    topic = models.CharField(max_length=200, unique=True) 
    slug = models.SlugField(blank=True, max_length=200)
    views = models.PositiveIntegerField(default=0)
    starter = models.ForeignKey(get_user_model(), related_name="topics", on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()

    def __str__(self):
        return self.topic


    def save(self, *args, **kwargs):
        self.slug = slugify(self.topic)
        return super().save(*args, **kwargs)
    

class Post(models.Model):
    topic = models.ForeignKey(Topic, related_name='posts',on_delete=models.CASCADE)
    post = MartorField()
    slug = models.SlugField(blank=True, max_length=200)
    created_by = models.ForeignKey(get_user_model(), related_name='posts', on_delete=models.CASCADE)
    updated_by = models.ForeignKey(get_user_model(), related_name="+", on_delete=models.CASCADE, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()


    def __str__(self):
        return self.post

    def save(self, *args, **kwargs):
        self.slug = slugify(self.topic)
        return super().save(*args, **kwargs)

    def get_post_as_markdown(self):
        return mark_safe(markdown(self.post, safe_mode='escape'))
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Forum{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" type="text/css" rel="stylesheet">
    <!-- <link href="https://myCDN.com/prism@v1.x/themes/prism.css" rel="stylesheet" /> -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
</head>
<body class="bg-dark">
    {% include 'messages.html' %}
    <header class="navbar-dark dark-color">
        <div class="container">
            <!--Navbar-->
            <nav class="navbar navbar-expand-md">
                <!-- Navbar brand -->
                <a class="navbar-brand" href="{% url 'pages:home' %}">Forum</a>
            
                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
            
                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">
                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link btn btn-dark" style="text-transform: capitalize;" href="mailto:jokotoyeademola95@gmail.com">Get in touch</a>
                        </li>
                    </ul>
                    <!-- Links -->
                    <!-- Dropdown -->
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle btn btn-dark" id="navbarDropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false"><i class="far fa-user mr-1"></i>{{ request.user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
                            <a class="dropdown-item" href="{% url 'profiles:profile' %}">Update account</a>
                            <a class="dropdown-item" href="{% url 'account_email' %}">Set E-mail</a>
                            <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
                        </div>
                    </li>
                    <a class="btn btn-dark" href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt mr-1"></i>Logout</a>
                    {% else %}
                    <a class="btn btn-light" href="{% url 'account_login' %}">Log in</a> |
                    <a class="btn btn-light" href="{% url 'account_signup' %}">Sign up</a>
                    {% endif %}
                    <form method="GET" action="{% url 'boards:search' %}" class="form-inline">
                        <div class="md-form my-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search"  name="q" aria-label="Search">
                        </div>
                    </form>
                </div>
                <!-- Collapsible content -->
            </nav>
        <!--/.Navbar-->
        </div>
    </header>
    {% block image_header %} 
    {% endblock %}
    <div class="">
        <a class="btn btn-success" style="text-transform: lowercase;" href="mailto:jokotoyeademola95@gmail.com">jokotoyeademola95@gmail.com</a>
    </div>
    {% block content %} 
    {% endblock %}
    <footer>
        <div class="text-center rounded text-white">
            <div class="my-4">
                <p>© 2020 | Developed By Ademola_oba</p>
            </div>
        </div>
    </footer>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <!-- <script src="https://myCDN.com/prism@v1.x/components/prism-core.min.js"></script>
	<script src="https://myCDN.com/prism@v1.x/plugins/autoloader/prism-autoloader.min.js"></script> -->
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.0/js/mdb.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block title %}Forum-Home{% endblock %}


{% block image_header %}
<img src="{% static 'images/original.jpg' %}" alt="" width="100%">
{% endblock %}


{% block content %}
<div class="container my-5">
    <main role="main">
        <div class="row justify-content-center">
            <div class="col-md-9">
                <div class="card">
                    <div class="text-center card-header">
                        <h2>Here are the available boards</h2>
                        <!-- <p>{{ request.session.session_key }}</p> -->
                    </div>
                    <div class="card-body">
                        <div class="table-responsive-md">
                            <table class="table table-hover table-bordered ">
                                <thead class="thead-dark">
                                    <tr>
                                        <th scope="col">#</td>
                                        <th scope="col">Board</th>
                                        <th scope="col">Topics</th>
                                        <th scope="col">Posts</th>
                                        <th scope="col">Last Post</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for board in board_list %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td>
                                            <h3><a href="{% url 'boards:board_topics' board.slug %}">{{ board }}</a></h3>
                                            <small class="d-block text-muted"><a href="{% url 'boards:board_topics' board.slug %}">{{ board.description }}</a></small>
                                            <small class="badge badge-pill badge-{{ board.get_badge_display }}">{{ board }} x {{ board.topics.count }}</small>
                                        </td>
                                        <td class="align-middle">{{ board.topics.count }}</td>
                                        <td class="align-middle">{{ board.get_post_count }}</td>
                                        {% if  board.get_last_post.created_by %}
                                        <td class="align-middle">By {{ board.get_last_post.created_by }} | {{ board.get_last_post.created_on|naturaltime }}
                                        {% else %}
                                        <td class="align-middle">No posts yet!</td>
                                        {% endif %}
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" style="margin: 0;">
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <i class="fas fa-times"></i>
            </button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{request.user}} account{% endblock %}



{% block content %}
<main class="container my-5" role="main">
    <div class="row justify-content-center">
        <div class="col-md-9">
            <div class="card">
                <div class="card-header text-center bg-dark">
                    <img class="text-center mb-2" src="{{ request.user.profile.image.url }}" alt="" width="50%">
                    {% if request.user.get_full_name %}
                    <h3 class="text-white">Welcome here {{ request.user.get_full_name }}!</h3>
                    {% else %}
                    <h3 class="text-white">Welcome here {{ request.user.username }}!</h3>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form_user|crispy }}
                        {{form_profile|crispy }}
                        <button class="btn btn-dark">update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}Forum-search?q={{q}}{% endblock %}



{% block content %}
    <div class="container my-5">
        <main role="main">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <section class="card-body ">
                            {% if not search_list %}
                            <p>No search found!</p>
                            {% else %}
                            <p>Here are your results!</p>
                            {% for topic in search_list %}
                            <ul>
                                <li>
                                    <a href="{% url 'boards:topic_posts' topic.board.slug topic.slug topic.pk %}">{{ topic }}</a>
                                </li>
                            </ul>
                            {% endfor %}
                            {% endif %}
                        </section>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}